"use client";
import { useMemo,useState } from "react"; import { Activity,BarChart3,BookOpen,CalendarDays,ChevronDown,CircleDollarSign,LayoutDashboard,Menu,Plus,Settings,ShieldCheck,Target,TrendingDown,TrendingUp,WalletCards,X } from "lucide-react"; import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { MetricCard } from "@/components/MetricCard"; import { TradeModal } from "@/components/TradeModal"; import { accounts as seedAccounts,trades as seedTrades } from "@/lib/sample-data"; import { NewTrade,Trade } from "@/lib/types"; import { isDemoMode,supabase } from "@/lib/supabase";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0,signDisplay:"auto"}).format(n);
export default function Home(){const [tab,setTab]=useState("Dashboard");const [trades,setTrades]=useState(seedTrades);const [modal,setModal]=useState(false);const [nav,setNav]=useState(false);
 const stats=useMemo(()=>{const pnl=trades.reduce((s,t)=>s+t.pnl,0),wins=trades.filter(t=>t.pnl>0),losses=trades.filter(t=>t.pnl<0),gross=wins.reduce((s,t)=>s+t.pnl,0),lost=Math.abs(losses.reduce((s,t)=>s+t.pnl,0));return {pnl,wins:wins.length,rate:trades.length?wins.length/trades.length*100:0,pf:lost?gross/lost:0,avg:trades.length?pnl/trades.length:0}},[trades]);
 const chart=useMemo(()=>[...trades].sort((a,b)=>a.closedAt.localeCompare(b.closedAt)).reduce<{date:string;pnl:number}[]>((a,t)=>{a.push({date:new Date(t.closedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"}),pnl:(a.at(-1)?.pnl||0)+t.pnl});return a},[]),[trades]);
 async function addTrade(t:NewTrade){const item={...t,id:crypto.randomUUID()};setTrades(v=>[item,...v]);setModal(false);if(supabase){const {error}=await supabase.from("trades").insert(item);if(error) console.error("Supabase insert failed",error.message)}}
 const navItems=[["Dashboard",LayoutDashboard],["Trades",BookOpen],["Accounts",WalletCards],["Analytics",BarChart3],["Calendar",CalendarDays],["Settings",Settings]] as const;
 return <div className="app"><aside className={nav?"open":""}><div className="brand"><div><Activity/></div><b>Trade<span>Flow</span></b><button onClick={()=>setNav(false)}><X/></button></div><nav>{navItems.map(([n,I])=><button key={n} className={tab===n?"selected":""} onClick={()=>{setTab(n);setNav(false)}}><I size={19}/>{n}</button>)}</nav><div className="aside-foot"><div className="avatar">UR</div><div><b>Usama Raja</b><small>Prop trader</small></div><ChevronDown size={16}/></div></aside><main><header className="top"><button className="mobile-menu" onClick={()=>setNav(true)}><Menu/></button><div><h1>{tab}</h1><p>{tab==="Dashboard"?"Your trading performance, at a glance.":`Review your ${tab.toLowerCase()} workspace.`}</p></div><div className="top-actions">{isDemoMode&&<span className="demo">Sample data</span>}<button className="primary" onClick={()=>setModal(true)}><Plus size={17}/>Add trade</button></div></header>
 {tab==="Dashboard"&&<><section className="metrics"><MetricCard label="Net P&L" value={money(stats.pnl)} detail="Across all accounts" icon={CircleDollarSign}/><MetricCard label="Win rate" value={`${stats.rate.toFixed(1)}%`} detail={`${stats.wins} of ${trades.length} trades won`} icon={Target} tone="blue"/><MetricCard label="Profit factor" value={stats.pf.toFixed(2)} detail="Gross profit / loss" icon={TrendingUp}/><MetricCard label="Avg. trade" value={money(stats.avg)} detail="Per closed trade" icon={Activity} tone={stats.avg>=0?"green":"red"}/></section><section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-head"><div><h2>Equity curve</h2><p>Cumulative realized profit</p></div><span className="positive">{money(stats.pnl)}</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#31d896" stopOpacity=".35"/><stop offset="1" stopColor="#31d896" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#263148" vertical={false}/><XAxis dataKey="date" stroke="#778198" fontSize={12}/><YAxis stroke="#778198" fontSize={12}/><Tooltip contentStyle={{background:"#111827",border:"1px solid #29334a",borderRadius:10}}/><Area type="monotone" dataKey="pnl" stroke="#31d896" strokeWidth={2.5} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></article><article className="panel accounts-panel"><div className="panel-head"><div><h2>Accounts</h2><p>Balance & rule health</p></div><button onClick={()=>setTab("Accounts")}>View all</button></div>{seedAccounts.map(a=><div className="account" key={a.id}><div className="account-icon"><WalletCards/></div><div><b>{a.name}</b><small>{a.firm} · {a.platform}</small></div><div className="account-value"><b>{money(a.balance)}</b><small className="positive">+{((a.balance/a.startingBalance-1)*100).toFixed(2)}%</small></div></div>)}<div className="rule"><ShieldCheck/><span>All account rules are within limits</span></div></article></section></>}
 {(tab==="Trades"||tab==="Dashboard")&&<section className="panel table-panel"><div className="panel-head"><div><h2>Recent trades</h2><p>Your latest closed positions</p></div>{tab==="Dashboard"&&<button onClick={()=>setTab("Trades")}>View all</button>}</div><div className="table-wrap"><table><thead><tr><th>Trade</th><th>Account</th><th>Side</th><th>Entry / Exit</th><th>Setup</th><th>Closed</th><th>P&amp;L</th></tr></thead><tbody>{trades.slice(0,tab==="Dashboard"?5:99).map(t=>{const a=seedAccounts.find(x=>x.id===t.accountId);return <tr key={t.id}><td><b>{t.symbol}</b><small>{t.lots} lots</small></td><td>{a?.name}</td><td><span className={`side ${t.side.toLowerCase()}`}>{t.side}</span></td><td><b>{t.entry}</b><small>{t.exit}</small></td><td>{t.setup}</td><td>{new Date(t.closedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</td><td className={t.pnl>=0?"positive":"negative"}>{money(t.pnl)}</td></tr>})}</tbody></table></div></section>}
 {tab==="Accounts"&&<section className="cards">{seedAccounts.map(a=><article className="panel account-card" key={a.id}><div className="panel-head"><div><small>{a.firm}</small><h2>{a.name}</h2></div><span className="status">{a.status}</span></div><strong>{money(a.balance)}</strong><p>Started at {money(a.startingBalance)} · {a.platform}</p><div className="limits"><span>Daily limit <b>{money(a.dailyLimit)}</b></span><span>Max limit <b>{money(a.maxLimit)}</b></span></div></article>)}</section>}
 {tab==="Analytics"&&<section className="cards"><article className="panel insight"><TrendingUp/><h2>Best setup</h2><strong>Trend continuation</strong><p>Two wins and {money(1320)} realized profit.</p></article><article className="panel insight"><TrendingDown/><h2>Largest loss</h2><strong>{money(Math.min(...trades.map(t=>t.pnl)))}</strong><p>Review losing trades and add journal notes.</p></article><article className="panel insight"><Target/><h2>Expectancy</h2><strong>{money(stats.avg)}</strong><p>Average return for every trade taken.</p></article></section>}
 {!["Dashboard","Trades","Accounts","Analytics"].includes(tab)&&<section className="panel empty"><Activity/><h2>{tab} is ready for your data</h2><p>This MVP includes the navigation destination; richer {tab.toLowerCase()} tools can be added next.</p></section>}</main>{modal&&<TradeModal accounts={seedAccounts} onClose={()=>setModal(false)} onSave={addTrade}/>}</div>}
